/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DepreciationRate;

import java.text.NumberFormat;
import java.util.Locale;

/**
 *
 * @author Kelly Meyer
 */
public class DecliningBalanceMethod extends javax.swing.JInternalFrame {

    /**
     * Creates new form DecliningBalanceMethod
     */
    public DecliningBalanceMethod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDcliningBalanceMethod = new javax.swing.JLabel();
        lblCostAmount = new javax.swing.JLabel();
        lblResidualValue = new javax.swing.JLabel();
        lblUsefulLife = new javax.swing.JLabel();
        lblDepreciationRate = new javax.swing.JLabel();
        txtInput1 = new javax.swing.JTextField();
        txtInput2 = new javax.swing.JTextField();
        txtUsefulLife = new javax.swing.JTextField();
        txtInput4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCalculate = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximizable(true);
        setTitle("Declining Balance Method");
        setPreferredSize(new java.awt.Dimension(470, 370));

        lblDcliningBalanceMethod.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        lblDcliningBalanceMethod.setText("Declining Balance Method");

        lblCostAmount.setFont(new java.awt.Font("Arial Nova", 1, 12)); // NOI18N
        lblCostAmount.setText("Cost Amount");

        lblResidualValue.setFont(new java.awt.Font("Arial Nova", 1, 12)); // NOI18N
        lblResidualValue.setText("Residual Value");

        lblUsefulLife.setFont(new java.awt.Font("Arial Nova", 1, 12)); // NOI18N
        lblUsefulLife.setText("Useful Life");

        lblDepreciationRate.setFont(new java.awt.Font("Arial Nova", 1, 12)); // NOI18N
        lblDepreciationRate.setText("Depreciation Rate");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnCalculate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCostAmount)
                            .addComponent(lblResidualValue)
                            .addComponent(lblUsefulLife)
                            .addComponent(lblDepreciationRate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInput1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInput2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsefulLife, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInput4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(lblDcliningBalanceMethod, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(81, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDcliningBalanceMethod)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCostAmount)
                    .addComponent(txtInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResidualValue)
                    .addComponent(txtInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsefulLife)
                    .addComponent(txtUsefulLife, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepreciationRate)
                    .addComponent(txtInput4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalculate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
      int intInput1;
      int intInput2;
      int intInput3;
      int intInput4;
      int intOutput;
      intInput1 = Integer.parseInt(txtInput1.getText());
      intInput2 = Integer.parseInt(txtInput2.getText());
      intInput4 = Integer.parseInt(txtInput4.getText());
      intOutput = intInput1 - intInput2 * intInput4;
      jTextArea1.setText(String.valueOf("Value at the end of1year(s) is :8000"+intOutput));
      
     double CostAmount = Double.parseDouble(txtInput1.getText());
     double ResidualValue = Double.parseDouble(txtInput2.getText());
     double UsefulLife = Double.parseDouble(txtUsefulLife.getText());
     double DepreciationRate = Double.parseDouble(txtInput4.getText())/100;
     int DepreciationAmount;
     int actual_year_amount =0;

     //create NumberFormat for currency in US Dollar format
     NumberFormat moneyFormat = NumberFormat.getCurrencyInstance(Locale.US);
        double years = 0;

    //create JTextArea output
    //JTextArea.output.TextArea = JTextArea ();
    //set first line of text in Output TextArea
    //output.TextArea.setText("Value at the end of "+year+" year(s) is:\n");
    //calculate amount on deposit for each ten year
     while(years<UsefulLife){
         years++;
         
     if(years<=1){
         
     DepreciationAmount = (int)(DepreciationRate*(CostAmount-ResidualValue));
     actual_year_amount = (int)((CostAmount-ResidualValue)-DepreciationAmount);
     System.out.println("Value at the end of "+years+" year(s) is: "+actual_year_amount);
     
     }
     else{
      actual_year_amount= actual_year_amount*1;
      DepreciationAmount = (int) (DepreciationRate*actual_year_amount);
      actual_year_amount = actual_year_amount - DepreciationAmount;
      System.out.println("Value at the end of "+years+" year(s is "+actual_year_amount);
     }
     }
     
     
     
     
      
         
     
     
              
    }//GEN-LAST:event_btnCalculateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCostAmount;
    private javax.swing.JLabel lblDcliningBalanceMethod;
    private javax.swing.JLabel lblDepreciationRate;
    private javax.swing.JLabel lblResidualValue;
    private javax.swing.JLabel lblUsefulLife;
    private javax.swing.JTextField txtInput1;
    private javax.swing.JTextField txtInput2;
    private javax.swing.JTextField txtInput4;
    private javax.swing.JTextField txtUsefulLife;
    // End of variables declaration//GEN-END:variables
}
