/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DepreciationRate;

/**
 *
 * @author Kelly Meyer
 */
public class StraightLineMethod extends javax.swing.JInternalFrame {

    /**
     * Creates new form StraightLineMethod
     */
    public StraightLineMethod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStraightLineMethod = new javax.swing.JLabel();
        lblCostOfTheAsset = new javax.swing.JLabel();
        lblEstimatedSalvageValue = new javax.swing.JLabel();
        lblLifeOfTheAsset = new javax.swing.JLabel();
        lblTotalDepreciationCost = new javax.swing.JLabel();
        lblAnnualDepreciationAmount = new javax.swing.JLabel();
        lblDepreciationRate = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        CostField = new javax.swing.JTextField();
        SalvageField = new javax.swing.JTextField();
        LifeField = new javax.swing.JTextField();
        TotalDepreciationField = new javax.swing.JTextField();
        AnnualDepreciationField = new javax.swing.JTextField();
        DepreciationRateField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximizable(true);
        setTitle("Staight-Line Method");
        setPreferredSize(new java.awt.Dimension(470, 370));

        lblStraightLineMethod.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        lblStraightLineMethod.setText("Straight-Line Method");

        lblCostOfTheAsset.setFont(new java.awt.Font("Arial Nova", 1, 12)); // NOI18N
        lblCostOfTheAsset.setText("Cost of The Asset");

        lblEstimatedSalvageValue.setFont(new java.awt.Font("Arial Nova", 1, 12)); // NOI18N
        lblEstimatedSalvageValue.setText("Estimated Salvage Value");

        lblLifeOfTheAsset.setFont(new java.awt.Font("Arial Nova", 1, 12)); // NOI18N
        lblLifeOfTheAsset.setText("Life of The Asset");

        lblTotalDepreciationCost.setFont(new java.awt.Font("Arial Nova", 1, 12)); // NOI18N
        lblTotalDepreciationCost.setText("Total Depreciation Cost");

        lblAnnualDepreciationAmount.setFont(new java.awt.Font("Arial Nova", 1, 12)); // NOI18N
        lblAnnualDepreciationAmount.setText("Annual Depreciation Amount");

        lblDepreciationRate.setFont(new java.awt.Font("Arial Nova", 1, 12)); // NOI18N
        lblDepreciationRate.setText("Depreciation Rate");

        btnCalculate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        TotalDepreciationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalDepreciationFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStraightLineMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstimatedSalvageValue)
                            .addComponent(lblCostOfTheAsset)
                            .addComponent(lblLifeOfTheAsset)
                            .addComponent(lblTotalDepreciationCost)
                            .addComponent(lblAnnualDepreciationAmount)
                            .addComponent(lblDepreciationRate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CostField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SalvageField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LifeField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalDepreciationField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnnualDepreciationField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DepreciationRateField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStraightLineMethod)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCostOfTheAsset)
                    .addComponent(CostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstimatedSalvageValue)
                    .addComponent(SalvageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLifeOfTheAsset)
                    .addComponent(LifeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalDepreciationCost)
                    .addComponent(TotalDepreciationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnnualDepreciationAmount)
                    .addComponent(AnnualDepreciationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepreciationRate)
                    .addComponent(DepreciationRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalculate)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TotalDepreciationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalDepreciationFieldActionPerformed
       
    }//GEN-LAST:event_TotalDepreciationFieldActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
      double a=Double.parseDouble(CostField.getText());
      double b=Double.parseDouble(SalvageField.getText());
      double amt=a-b;
      
      double discount=amt/5;
      
      DepreciationRateField.setText("20");
       // double d=Double.parseDouble(DepreciationRateField.setName("20")
       
       TotalDepreciationField.setText(""+amt);
       
       AnnualDepreciationField.setText(""+discount);
       // DepreciationRateField.setText(""-d);
       
         
    }//GEN-LAST:event_btnCalculateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnnualDepreciationField;
    private javax.swing.JTextField CostField;
    private javax.swing.JTextField DepreciationRateField;
    private javax.swing.JTextField LifeField;
    private javax.swing.JTextField SalvageField;
    private javax.swing.JTextField TotalDepreciationField;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel lblAnnualDepreciationAmount;
    private javax.swing.JLabel lblCostOfTheAsset;
    private javax.swing.JLabel lblDepreciationRate;
    private javax.swing.JLabel lblEstimatedSalvageValue;
    private javax.swing.JLabel lblLifeOfTheAsset;
    private javax.swing.JLabel lblStraightLineMethod;
    private javax.swing.JLabel lblTotalDepreciationCost;
    // End of variables declaration//GEN-END:variables
}
